version: '3.8'

services:
  bt-recover-dev:
    build: 
      context: .
      target: builder
    volumes:
      - .:/app
      - ./output:/home/appuser/output
    working_dir: /app
    command: ["pytest", "-v"]
    environment:
      - PYTHONPATH=/app/src 